from django.db import migrations


def dropDown(apps, schema_editor):
    groupMaster = apps.get_model('tracker_api', 'groupMaster')
    groupMaster.objects.bulk_create([
        groupMaster(group='Practice', value='DotNet', label='DotNet'),
        groupMaster(group='Practice', value='BI', label='BI'),
        groupMaster(group='Practice', value='Data', label='Data'),
        groupMaster(group='Practice', value='DataScience', label='DataScience'),
        groupMaster(group='Practice', value='MSDynamics', label='MSDynamics'),
        groupMaster(group='Practice', value='JS', label='JS'),
        groupMaster(group='Practice', value='PMO', label='PMO'),
        groupMaster(group='Practice', value='ROR', label='ROR'),
        groupMaster(group='Practice', value='Microsoft', label='Microsoft'),
        groupMaster(group='Practice', value='Devops', label='Devops'),
        groupMaster(group='Practice', value='QA', label='QA'),
        groupMaster(group='Practice', value='DataEngineering', label='DataEngineering'),
        groupMaster(group='Practice', value='Python', label='Python'),
        groupMaster(group='Practice', value='Scrum', label='Scrum'),
        groupMaster(group='Practice', value='TechnicalManager', label='TechnicalManager'),
        groupMaster(group='Practice', value='OpenSource', label='OpenSource'),
        groupMaster(group='Practice', value='AIML', label='AIML'),
        groupMaster(group='Practice', value='Java', label='Java'),
        groupMaster(group='Practice', value='RPA', label='RPA'),
        groupMaster(group='Practice', value='Other', label='Other'),
        groupMaster(group='Practice', value='Cloud', label='Cloud'),
        groupMaster(group='Practice', value='Mobile', label='Mobile'),
        groupMaster(group='Practice', value='BusinessAnalyst', label='BusinessAnalyst'),
        groupMaster(group='Practice', value='Architect', label='Architect'),
        groupMaster(group='Practice', value='JSFramework', label='JSFramework'),
        groupMaster(group='Source', value='JobPortals', label='JobPortals'),
        groupMaster(group='Source', value='Linkedin', label='Linkedin'),
        groupMaster(group='Source', value='Referral', label='Referral'),
        groupMaster(group='Source', value='IJP', label='IJP'),
        groupMaster(group='Source', value='VendorFulltime', label='VendorFulltime'),
        groupMaster(group='Source', value='Rehire', label='Rehire'),
        groupMaster(group='Source', value='SocialMedia', label='SocialMedia'),
        groupMaster(group='Source', value='SubconVendors', label='SubconVendors'),
        groupMaster(group='Source', value='Other', label='Other'),
        groupMaster(group='Source2', value='Naukri', label='Naukri'),
        groupMaster(group='Source2', value='Linkedin', label='Linkedin'),
        groupMaster(group='Source2', value='Vaakruthi', label='Vaakruthi'),
        groupMaster(group='Source2', value='Kollasoft', label='Kollasoft'),
        groupMaster(group='Source2', value='Sigma', label='Sigma'),
        groupMaster(group='Source2', value='Sanvartech', label='Sanvartech'),
        groupMaster(group='Source2', value='Randstad', label='Randstad'),
        groupMaster(group='Source2', value='Cbrex', label='Cbrex'),
        groupMaster(group='Source2', value='Refrral', label='Referral'),
        groupMaster(group='Source2', value='Culminant', label='Culminant'),
        groupMaster(group='Source2', value='ACS-Ashwini', label='ACS-Ashwini'),
        groupMaster(group='Source2', value='ACS-Pradeep', label='ACS-Pradeep'),
        groupMaster(group='Source2', value='AeGan', label='AeGan'),
        groupMaster(group='Source2', value='Maxima', label='Maxima'),
        groupMaster(group='Source2', value='Ikrux', label='Ikrux'),
        groupMaster(group='Source2', value='Promitheiatech', label='Promitheiatech'),
        groupMaster(group='Source2', value='MAZ ELEVEN', label='MAX ELEVEN'),
        groupMaster(group='Source2', value='Other', label='Other'),
        groupMaster(group='Status', value='Sourced', label='Sourced'),
        groupMaster(group='Status', value='ScreenReject', label='ScreenReject'),
        groupMaster(group='Status', value='ResumeShortListed', label='ResumeShortListed'),
        groupMaster(group='Status', value='NoShow', label='NoShow'),
        groupMaster(group='Status', value='L1InterviewScheduled', label='L1InterviewScheduled'),
        groupMaster(group='Status', value='L1InterviewSelect', label='L1InterviewSelect'),
        groupMaster(group='Status', value='L1InterviewReject', label='L1InterviewReject'),
        groupMaster(group='Status', value='L1InterviewFeedbackAwaited', label='L1InterviewFeedbackAwaited'),
        groupMaster(group='Status', value='L2InterviewScheduled', label='L2InterviewScheduled'),
        groupMaster(group='Status', value='L2InterviewSelect', label='L2InterviewSelect'),
        groupMaster(group='Status', value='L2InterviewReject', label='L2InterviewReject'),
        groupMaster(group='Status', value='L2InterviewFeedbackAwaited', label='L2InterviewFeedbackAwaited'),
        groupMaster(group='Status', value='Offered', label='Offered'),
        groupMaster(group='Status', value='OfferAccepted', label='OfferAccepted'),
        groupMaster(group='Status', value='OfferDeclined', label='OfferDeclined'),
        groupMaster(group='Status', value='Joined', label='Joined'),
        groupMaster(group='Status', value='OfferOnhold', label='OfferOnhold'),
        groupMaster(group='Status', value='FitmentReject', label='FitmentReject'),
        groupMaster(group='Status', value='Withdrawn', label='Withdrawn'),
        groupMaster(group='DeclineReasons', value='WFHPermanent', label='WFHPermanent'),
        groupMaster(group='DeclineReasons', value='BetterOffer', label='BetterOffer'),
        groupMaster(group='DeclineReasons', value='Retained', label='Retained'),
        groupMaster(group='DeclineReasons', value='Onshore', label='Onshore'),
        groupMaster(group='DeclineReasons', value='PersonalReasons', label='PersonalReasons'),
        groupMaster(group='DeclineReasons', value='MedicalReasons', label='MedicalReasons'),
        groupMaster(group='DeclineReasons', value='LocationConstraints', label='LocationConstraints'),
        groupMaster(group='DeclineReasons', value='NotResponding', label='NotResponding'),
        groupMaster(group='DeclineReasons', value='OfferRevoke', label='OfferRevoke'),
        groupMaster(group='Gender', value='Male', label='Male'),
        groupMaster(group='Gender', value='Female', label='Female'),
        groupMaster(group='Gender', value='Other', label='Other'),
        groupMaster(group='OfferGrade', value='L1', label='L1'),
        groupMaster(group='OfferGrade', value='L2 A', label='L2 A'),
        groupMaster(group='OfferGrade', value='L2 B', label='L2 B'),
        groupMaster(group='OfferGrade', value='L3 A', label='L3 A'),
        groupMaster(group='OfferGrade', value='L3 B', label='L3 B'),
        groupMaster(group='OfferGrade', value='L4 A', label='L4 A'),
        groupMaster(group='OfferGrade', value='L4 B', label='L4 B'),
        groupMaster(group='OfferGrade', value='L5 A', label='L5 A'),
        groupMaster(group='OfferGrade', value='L5 B', label='L5 B'),
        groupMaster(group='OfferGrade', value='L6', label='L6'),
        groupMaster(group='OfferGrade', value='L7', label='L7'),
        groupMaster(group='OfferGrade', value='L8', label='L8'),
        groupMaster(group='OfferGrade', value='L9', label='L9'),
        groupMaster(group='OfferGrade', value='L10', label='L10'),
        groupMaster(group='OfferGrade', value='L11', label='L11'),
        groupMaster(group='OfferGrade', value='C', label='C'),
        groupMaster(group='OfferGrade', value='L12', label='L12'),
        groupMaster(group='OfferGrade', value='L5', label='L5'),
        groupMaster(group='SubSource', value='Naukri', label='Naukri'),
        groupMaster(group='SubSource', value='Linkedin', label='Linkedin'),
        groupMaster(group='SubSource', value='Vaakruthi', label='Vaakruthi'),
        groupMaster(group='SubSource', value='Kollasoft', label='Kollasoft'),
        groupMaster(group='SubSource', value='Sigma', label='Sigma'),
        groupMaster(group='SubSource', value='Sanvartech', label='Sanvartech'),
        groupMaster(group='SubSource', value='Randstad', label='Randstad'),
        groupMaster(group='SubSource', value='Cbrex', label='Cbrex'),
        groupMaster(group='SubSource', value='Refrral', label='Referral'),
        groupMaster(group='SubSource', value='Culminant', label='Culminant'),
        groupMaster(group='SubSource', value='ACS-Ashwini', label='ACS-Ashwini'),
        groupMaster(group='SubSource', value='ACS-Pradeep', label='ACS-Pradeep'),
        groupMaster(group='SubSource', value='AeGan', label='AeGan'),
        groupMaster(group='SubSource', value='Maxima', label='Maxima'),
        groupMaster(group='SubSource', value='Ikrux', label='Ikrux'),
        groupMaster(group='SubSource', value='Promitheiatech', label='Promitheiatech'),
        groupMaster(group='SubSource', value='MAZ ELEVEN', label='MAX ELEVEN'),
        groupMaster(group='SubSource', value='Other', label='Other'),
        groupMaster(group='Grade', value='L1', label='L1'),
        groupMaster(group='Grade', value='L2 A', label='L2 A'),
        groupMaster(group='Grade', value='L2 B', label='L2 B'),
        groupMaster(group='Grade', value='L3 A', label='L3 A'),
        groupMaster(group='Grade', value='L3 B', label='L3 B'),
        groupMaster(group='Grade', value='L4 A', label='L4 A'),
        groupMaster(group='Grade', value='L4 B', label='L4 B'),
        groupMaster(group='Grade', value='L5 A', label='L5 A'),
        groupMaster(group='Grade', value='L5 B', label='L5 B'),
        groupMaster(group='Grade', value='L6', label='L6'),
        groupMaster(group='Grade', value='L7', label='L7'),
        groupMaster(group='Grade', value='L8', label='L8'),
        groupMaster(group='Grade', value='L9', label='L9'),
        groupMaster(group='Grade', value='L10', label='L10'),
        groupMaster(group='Grade', value='L11', label='L11'),
        groupMaster(group='Grade', value='C', label='C'),
        groupMaster(group='Grade', value='L12', label='L12'),
        groupMaster(group='Grade', value='L5', label='L5'),
        groupMaster(group='Status', value='Cancelled', label='Cancelled'),
        groupMaster(group='Status', value='Filled', label='Filled'),
        groupMaster(group='Status', value='Open', label='Open'),
        groupMaster(group='Status', value='FilledInternally', label='FilledInternally'),
        groupMaster(group='Status', value='Closed', label='Closed'),
        groupMaster(group='Status', value='ApprovalAwaited', label='ApprovalAwaited'),
        groupMaster(group='Status', value='OnHold', label='OnHold'),
        groupMaster(group='CurrentWeekPriority', value='Low', label='Low'),
        groupMaster(group='CurrentWeekPriority', value='Medium', label='Medium'),
        groupMaster(group='CurrentWeekPriority', value='High', label='High'),
        groupMaster(group='PMO Status', value='N/A', label='N/A'),
        groupMaster(group='PMO Status', value='Allocated', label='Allocated'),
        groupMaster(group='PMO Status', value='Cancelled', label='Cancelled'),
        groupMaster(group='PMO Status', value='Approved', label='Approved'),
        groupMaster(group='PMO Status', value='ToHire', label='ToHire'),
        groupMaster(group='PMO Status', value='OnHold', label='OnHold'),
        groupMaster(group='PMO Status', value='Identified', label='Identified'),
        groupMaster(group='PMO Status', value='Open', label='Open'),
        groupMaster(group='PMO Status', value='Planned', label='Planned'),
        groupMaster(group='Perm/Subcon/Contract', value='Permanent', label='Permanent'),
        groupMaster(group='Perm/Subcon/Contract', value='Permanent/subcon', label='Permanent/subcon'),
        groupMaster(group='Perm/Subcon/Contract', value='Subcon', label='Subcon'),
        groupMaster(group='Perm/Subcon/Contract', value='Contract', label='Contract'),
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dropDown),
    ]
