# Generated by Django 4.0.8 on 2023-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0003_rename_label_groupmaster_name_groupmaster_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
